name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Run Linux commands
              run: | 
                echo "My first Github Actions job"
                ls -lha
                cat README.md
            
            - name: Generate ASCII art
              run: cowsay
