name: Generate Ascii Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Install cowsay
              uses: sudo apt-get install cowsay -y
            
            - name: Generate ASCII art
              run: cowsay
