name: Generate Ascii Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Check repo files
              run: ls -lha
            
            - name: Execute cowsay from script
              run: | 
                chmod +x ascii-script.sh
                ./ascii-script.sh
            
