name: Generate Ascii Artwork

on: push

jobs:
    ascii_job_build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Check repo files
              run: ls -lha
    
    ascii_job_deploy:
        runs-on: ubuntu-latest
        needs: ascii_job_build
        steps:
            - name: Run cowsay
              run: |
               sudo apt-get install cowsay -y 
               cowsay "Hello world!"
            
